# -*- coding: utf-8 -*-
"""Unit-3 Data summerization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZtHXehgK5aKV28GxBK90asRcd-5cYuY
"""

#Complete Summary of an Employee Dataset
import pandas as pd

# Create sample employee dataset
data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['John', 'Alice', 'Bob', 'David', 'Emma'],
    'Age': [25, 30, 28, None, 35],
    'Salary': [30000, 45000, 40000, 50000, None],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
}

df = pd.DataFrame(data)

# Number of rows and columns
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

# Data types
print("\nData Types:")
print(df.dtypes)

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Complete dataset
print("\nEmployee Dataset:")
print(df)

#Frequency Distribution of Students' Grades with Bar Chart
import pandas as pd
import matplotlib.pyplot as plt

# Sample grades
grades = ['A', 'B', 'A', 'C', 'B', 'A', 'D', 'B', 'C', 'A',
          'B', 'C', 'A', 'D', 'B']

# Frequency distribution
frequency = pd.Series(grades).value_counts().sort_index()

print("Grade Frequency:")
print(frequency)

# Bar chart
frequency.plot(kind='bar')

plt.xlabel("Grade")
plt.ylabel("Number of Students")
plt.title("Frequency Distribution of Students' Grades")
plt.show()

#Histogram of House Prices and Identify Skewness
import pandas as pd
import matplotlib.pyplot as plt

# Sample house prices
house_prices = [120000, 150000, 180000, 200000, 220000,
                250000, 270000, 300000, 350000, 400000,
                450000, 500000, 700000, 900000, 1200000]

df = pd.DataFrame({'House_Price': house_prices})

# Calculate skewness
skewness = df['House_Price'].skew()

print("Skewness:", skewness)

# Histogram
plt.hist(df['House_Price'], bins=8, edgecolor='black')

plt.xlabel("House Price")
plt.ylabel("Frequency")
plt.title("Histogram of House Prices")
plt.show()

# Identify distribution
if skewness > 0:
    print("The data is positively skewed (right-skewed).")
elif skewness < 0:
    print("The data is negatively skewed (left-skewed).")
else:
    print("The data is approximately normally distributed.")

#Box Plot of Salary Data and Identify Outliers
import pandas as pd
import matplotlib.pyplot as plt

# Sample salary data
salary = [25000, 28000, 30000, 32000, 35000,
          37000, 40000, 42000, 45000, 150000]

df = pd.DataFrame({'Salary': salary})

# Box plot
plt.boxplot(df['Salary'])

plt.ylabel("Salary")
plt.title("Box Plot of Salary Data")
plt.show()

# IQR method
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("\nOutliers:")
print(outliers)

#Detect Outliers in Students' Marks Using IQR
import pandas as pd

# Sample student marks
marks = [45, 50, 55, 60, 62, 65, 68, 70, 72, 75,
         78, 80, 82, 85, 150]

df = pd.DataFrame({'Marks': marks})

# Calculate Q1 and Q3
Q1 = df['Marks'].quantile(0.25)
Q3 = df['Marks'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Find limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)
print("Lower Limit =", lower_limit)
print("Upper Limit =", upper_limit)

# Detect outliers
outliers = df[
    (df['Marks'] < lower_limit) |
    (df['Marks'] > upper_limit)
]

print("\nOutliers:")
print(outliers)

import pandas as pd

# Sample sales data
sales = [1000, 1200, 1500, 1800, 2000, 2200,
         2500, 2700, 3000, 3200, 15000]

df = pd.DataFrame({'Sales': sales})

print("Original Dataset:")
print(df)

# Calculate Q1 and Q3
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)

# IQR
IQR = Q3 - Q1

# Limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Remove outliers
cleaned_df = df[
    (df['Sales'] >= lower_limit) &
    (df['Sales'] <= upper_limit)
]

print("\nCleaned Dataset:")
print(cleaned_df)

import pandas as pd
import matplotlib.pyplot as plt

# Sample dataset
data = [10, 12, 13, 15, 16, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 100]

df = pd.DataFrame({'Value': data})

# Calculate IQR
Q1 = df['Value'].quantile(0.25)
Q3 = df['Value'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Remove outliers
cleaned_df = df[
    (df['Value'] >= lower) &
    (df['Value'] <= upper)
]

# Histogram before removing outliers
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.hist(df['Value'], bins=8, edgecolor='black')
plt.title("Before Removing Outliers")
plt.xlabel("Value")
plt.ylabel("Frequency")

# Histogram after removing outliers
plt.subplot(1, 2, 2)
plt.hist(cleaned_df['Value'], bins=8, edgecolor='black')
plt.title("After Removing Outliers")
plt.xlabel("Value")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

# Box plots
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.boxplot(df['Value'])
plt.title("Box Plot Before")

plt.subplot(1, 2, 2)
plt.boxplot(cleaned_df['Value'])
plt.title("Box Plot After")

plt.tight_layout()
plt.show()

print("Original Data:")
print(df)

print("\nCleaned Data:")
print(cleaned_df)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df['species'] = iris.target_names[iris.target]

# Display first few rows
print("First 5 Rows:")
print(df.head())

# --------------------------------------------------
# 1. Dataset Information
# --------------------------------------------------

print("\nDataset Information:")
print(df.info())

# Number of rows and columns
print("\nShape of Dataset:")
print(df.shape)

# --------------------------------------------------
# 2. Missing Values
# --------------------------------------------------

print("\nMissing Values:")
print(df.isnull().sum())

# --------------------------------------------------
# 3. Descriptive Statistics
# --------------------------------------------------

print("\nDescriptive Statistics:")
print(df.describe())

# --------------------------------------------------
# 4. Histograms
# --------------------------------------------------

df.hist(figsize=(10, 8), bins=10, edgecolor='black')

plt.suptitle("Histograms of Iris Features")
plt.tight_layout()
plt.show()

# --------------------------------------------------
# 5. Box Plots
# --------------------------------------------------

plt.figure(figsize=(10, 6))

sns.boxplot(data=df.drop(columns='species'))

plt.title("Box Plots of Iris Features")
plt.xticks(rotation=20)
plt.show()

# --------------------------------------------------
# 6. Detect Outliers Using IQR
# --------------------------------------------------

numeric_columns = df.select_dtypes(include='number').columns

outlier_data = {}

for column in numeric_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    outlier_data[column] = len(outliers)

    print("\n", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Number of Outliers:", len(outliers))

# --------------------------------------------------
# 7. Remove Outliers
# --------------------------------------------------

cleaned_df = df.copy()

for column in numeric_columns:

    Q1 = cleaned_df[column].quantile(0.25)
    Q3 = cleaned_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    cleaned_df = cleaned_df[
        (cleaned_df[column] >= lower) &
        (cleaned_df[column] <= upper)
    ]

print("\nOriginal Dataset Shape:", df.shape)
print("Cleaned Dataset Shape:", cleaned_df.shape)

# --------------------------------------------------
# 8. Box Plot After Removing Outliers
# --------------------------------------------------

plt.figure(figsize=(10, 6))

sns.boxplot(data=cleaned_df[numeric_columns])

plt.title("Box Plots After Removing Outliers")
plt.xticks(rotation=20)
plt.show()

# --------------------------------------------------
# 9. Save Cleaned Dataset
# --------------------------------------------------

cleaned_df.to_csv("iris_cleaned.csv", index=False)

print("\nCleaned dataset saved as 'iris_cleaned.csv'")